// Generated by CoffeeScript 1.6.2
/*
  Gozer - A load tester
  
  @author Bheesham Peraud <bheesham.persaud@live.ca>
*/


(function() {
  var cli, fs, phantom, taunt, yaml;

  fs = require("fs");

  yaml = require("js-yaml");

  cli = require("cli-color");

  phantom = require('phantom-proxy');

  exports.log = function(msg, type) {
    if (type === "error") {
      return console.log(cli.red("ERROR: ") + msg);
    } else if (type === "success") {
      return console.log(cli.green("SUCCESS: ") + msg);
    } else {
      return console.log(msg);
    }
  };

  exports.config = function(file) {
    if (!fs.existsSync(file) || !fs.statSync(file).isFile()) {
      exports.log("Speficied configuration could not be found.", "error");
      process.exit(1);
    }
    return yaml.safeLoad(fs.readFileSync(file).toString());
  };

  exports.taunt = function(duration, config) {
    return phantom.create({
      ignoreSslErrors: true,
      diskCache: false,
      loadImages: true,
      maxDiskCache: 0
    }, taunt);
  };

  taunt = function(proxy, config) {
    return exports.log("boo!");
  };

}).call(this);
